### ISSUE TITLE
Missing "security" category in the scan result in intellij

### ISSUE THREAD

**Issue by MOURIK** [JetBrains/spotbugs-intellij-plugin#12]
Missing "security" category in the scan result. Before we have been using the findbugs plugin which display security category in the scan result. We lost "security" category since the migration to spotbugs plugin.
versions tested: 1.0.0 and 1.1.0.
Please find attached the screenshot with categories from the scan result that miss security category.
thanks in advance.
scan with spotbugs plugin:
<img width="394" alt="spotbugs_category" src="https://user-images.githubusercontent.com/16650493/78896469-d19eea00-7a70-11ea-8bcd-24204985810d.png">
scan with findbugs plugin:
<img width="394" alt="findbugs_category" src="https://user-images.githubusercontent.com/16650493/78896902-9a7d0880-7a71-11ea-9d39-27b4076a5239.png">

**Comment by jqyp** [comment]
Please, open «Preferences» → «SpotBugs» → «General» and make sure that «Find Security Bugs» is enabled. Then open the «Report» tab and check the checkbox «Security» in the «Reported (visible) bug categories» section. Finally check the «Detector» tab.

<img width="1012" alt="Screen Shot 2020-04-11 at 03 55 31" src="https://user-images.githubusercontent.com/56357688/79032742-92c47d80-7bb1-11ea-85ae-18f7d84a7a71.png">

![Screen Shot 2020-04-11 at 03 55 39](https://user-images.githubusercontent.com/56357688/79032753-aa9c0180-7bb1-11ea-872f-48d7aa9a4aa5.png)

<img width="1012" alt="Screen Shot 2020-04-11 at 04 12 14" src="https://user-images.githubusercontent.com/56357688/79032794-e8992580-7bb1-11ea-9be3-b400626692b4.png">

**Comment by jqyp** [comment]
Please, open "Preferences" → "SpotBugs" → "General" and make sure that "Find Security Bugs" is enabled. Then open the "Report" tab and check the "Security" checkbox in the "Reported (visible) bug categories" section. Finally check the "Detector" tab.

<img width="1012" alt="Screen Shot 2020-04-11 at 03 55 31" src="https://user-images.githubusercontent.com/56357688/79032742-92c47d80-7bb1-11ea-85ae-18f7d84a7a71.png">

![Screen Shot 2020-04-11 at 03 55 39](https://user-images.githubusercontent.com/56357688/79032753-aa9c0180-7bb1-11ea-872f-48d7aa9a4aa5.png)

<img width="1012" alt="Screen Shot 2020-04-11 at 04 12 14" src="https://user-images.githubusercontent.com/56357688/79032794-e8992580-7bb1-11ea-9be3-b400626692b4.png">

**Comment by amaembo** [comment]
Which issues exactly were reported in security category? Could they be supplied by third-party plugin (e.g. find-sec-bugs)?

**Comment by MOURIK** [comment]
Hello, 
Thanks very much for your speedy response, your colleague "jqyp" already reply to me directly in my email... after investigations, i fixed the issue. I had the issue because i had findbugs and spotbugs intellij plugins installed in the same time. Because of that when i run spotbug scan, the security category was missing in the result. but since i uninstalled findbugs plugin everyting seems to be good. Problem solved !
Thanks for support guys :)

**Comment by amaembo** [comment]
Great! I'm glad your problem is solved.
