### ISSUE TITLE
Hard fork Considerations or transfer to Spotbugs

### ISSUE THREAD

**Issue by hazendaz** [JetBrains/spotbugs-intellij-plugin#1572]
I'm one of the owners over at spotbugs.  We are inundated by improper maintenance here and even our tickets are going unanswered.  We are now starting a discussion to take this over as a hard fork unless you are willing to transfer ownership.  We would need some help in that transition such as how to release, etc.  Personally I feel it has to belong to us so long as Intellij keeps encouraging users to open tickets with us and it really appears this was abandoned at this point.

I know this will be hard to see as the same issue we are being faced with this project is too.  My gut tells me the 900 tickets are mostly incredibly junk due to how the auto reporting feature from intellij just provides incoherent tickets.

So please help us here...we cannot keep getting ticket after ticket where we are telling people we can do zero for them to come here and they get zero here too.  We would grant any actual contributors here access as part of spotbugs if it is transferred over but need a lot of help getting going with it as it would be new to us but we are active, releasing regularly and the problem is just getting worse.

**Comment by amaembo** [comment]
For now, I've updated the SpotBugs dependency and published the new version of the plugin, among doing other cleanups. Of course, you are free to create your own fork under the terms of the license.

**Comment by hazendaz** [comment]
@amaembo Thank you, should there be tagging and release notes applied?  Last tag is still 1.2.5.

**Comment by amaembo** [comment]
Done. That said, I don't promise that I'll continue support in the future. So if you'd like to take over the maintenance, that probably would be better for the community. You will need to change plugin ID though, and better to rename the root package, as it should not start from `org.jetbrains`. You can upload your plugin to plugin repository under new name (SpotBugs Neo, SpotBugs Reloaded, whatever), and after that I can retire our version and archive this repository.

From the architectural point of view, I think it would be preferred to run the SpotBugs in a forked process, outside of the main IntelliJ IDEA process. This would reduce possible problems with changes in IntelliJ platform and probably make the overall thing more stable. Not sure how hard it is though.

There are also a handful of unresolved compatibility problems (use of deprecated APIs, etc.)
