### ISSUE TITLE
Fix action names

### ISSUE THREAD

**Issue by amaembo** [JetBrains/spotbugs-intellij-plugin#4]
`SpotBugs` search results in "Run action by name" look not so pretty. Action names should be updated.

![image](https://user-images.githubusercontent.com/5114450/77720825-9be31580-701b-11ea-805f-0b4b41bb063e.png)

**Comment by jqyp** [comment]
Three groups with text "SpotBugs" have been merged into one here:
3f9e68d372317f0ca27d3222c8966ad5c82ccc51
