### ISSUE TITLE
Can't install the plugin in IDEA 2020.1.3

### ISSUE THREAD

**Issue by maslbl4** [JetBrains/spotbugs-intellij-plugin#47]
Can't install the plugin in IDEA 2020.1.3
OS: Windows 1909

`Plugin "SpotBugs" was not installed: Cannot download '/files/14014/91475/spotbugs-idea-1.2.3.zip?updateId=91475&pluginId=14014&family=INTELLIJ&uuid=f49a0b2a-303b-4135-9144-58b6f5870a96&code=IU&build=201.8538.31': no protocol: /files/14014/91475/spotbugs-idea-1.2.3.zip?updateId=91475&pluginId=14014&family=INTELLIJ&uuid=f49a0b2a-303b-4135-9144-58b6f5870a96&code=IU&build=201.8538.31`

**Comment by amaembo** [comment]
Probably there was a temporary problem on the plugin repository server. Please try again. In fact, plugin updates are handled by IntelliJ IDEA itself, not by the plugin code, so if the problem persists, it worth reporting to the IntelliJ IDEA issue tracker. Thanks.
