### ISSUE TITLE
Update third-party plugins

### ISSUE THREAD

**Issue by amaembo** [JetBrains/spotbugs-intellij-plugin#5]
See src\main\resources\org\twodividedbyzero\idea\findbugs\plugins. There are AndroidFindbugs_0.5.jar, fb-contrib-6.8.0.jar, findsecbugs-plugin-1.5.0.jar. Check whether new versions exist, update if necessary.

**Comment by lqc** [comment]
In case of my project findsecbugs 1.5 just crashes, so you really want to update those. It would be great if there was some way to use a version defined in a Maven/Gradle project.
